mysite/author/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^@(?P<author_slug>[\w-]+)/$', views.show_profile, name='show_profile'),
    url(r'^@(?P<author_slug>[\w-]+)/update/$', views.update_profile, name='update_profile'),
]

mysite/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.sign_in, name='sign_in'),
    url(r'^signout/$', views.sign_out, name='sign_out'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^', include('author.urls', namespace="author")),
    url(r'^', include('story.urls', namespace="story")),

]

if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/story/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^@(?P<author_slug>[\w-]+)/story/create/$', views.create_story, name='create_story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/edit/$', views.edit_story, name='edit_story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/$', views.story, name='story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/chapter/create$', views.create_chapter, name='create_chapter'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/(?P<chapter_slug>[\w-]+)/edit$', views.edit_chapter, name='edit_chapter'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/(?P<chapter_slug>[\w-]+)/$', views.chapter, name='chapter'),
    url(r'^home/$', views.home, name="home"),
    url(r'^topstories/$', views.top_stories, name="top_stories"),

]

mysite/templates/base.html
{% load staticfiles %}

<html>
<head>
  <title>
    {% block title %}
      Frame
    {% endblock %}
  </title>
  	{% block style %}
      <style>

      </style>
  	{% endblock style%}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/custom.css'%}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>


</head>
<body id="myPage">
  {% include 'navbar.html' %}
  {% block content%}
  {% endblock content %}

<script>

$(document).ready(function(){
    // Initialize Tooltip
    $('[data-toggle="tooltip"]').tooltip();
});
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $("footer a[href='#myPage']").on('click', function(event) {

  // Prevent default anchor click behavior
  event.preventDefault();

  // Store hash
  var hash = this.hash;

  // Using jQuery's animate() method to add smooth page scroll
  // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
  $('html, body').animate({
    scrollTop: $(hash).offset().top
  }, 900, function(){

    // Add hash (#) to URL when done scrolling (default click behavior)
    window.location.hash = hash;
    });
  });
})
</script>

</body>
</html>

mysite/templates/carousel.html
{% load staticfiles %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="{% static 'img/ny.jpg'%}" alt="New York">
      <div class="carousel-caption">
        <h3>New York</h3>
        <p>The atmosphere in New York is lorem ipsum.</p>
      </div>
    </div>

    <div class="item">
      <img src="{% static 'img/chicago.jpg'%}" alt="Chicago">
      <div class="carousel-caption">
        <h3>Chicago</h3>
        <p>Thank you, Chicago - A night we won't forget.</p>
      </div>
    </div>

    <div class="item">
      <img src="{% static 'img/la.jpg'%}" alt="Los Angeles">
      <div class="carousel-caption">
        <h3>LA</h3>
        <p>Even though the traffic was a mess, we had the best time.</p>
      </div>
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

mysite/templates/footer.html
<footer class="text-center navbar-fixed-bottom" style="bottom">
<!--   <a class="up-arrow" href="#myPage" data-toggle="tooltip" title="TO TOP">
    <span class="glyphicon glyphicon-chevron-up"></span>
  </a><br><br> -->
  <p>A perfect platform to post your stories...</p> 
</footer>

mysite/templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'main:main' %}">Logo</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'story:home' %}">Home</a></li>
        <li><a href="{% url 'story:top_stories' %}">Top Stories</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <form  action="{% url 'story:home' %}" method="GET">
                <input style="margin-top:10px;" name="q" placeholder="Search Stories" type="search" value="{{request.GET.q}}"/>
          </form>
        </li>
        <li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li>

        {% if not request.user.is_active %}
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">SIGN IN/UP
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'main:sign_in' %}">Sign In</a></li>
              <li class="divider"></li>
              <li><a href="{% url 'main:signup' %}">Sign Up</a></li>
            </ul>
          </li>
        {% else %}
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">{{request.user}}
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'story:create_story' request.user|slugify %}">New Story</a></li>
              <li class="divider"></li>
              <li><a href="{% url 'author:show_profile' request.user|slugify %}">Profile</a></li>
              <li><a href="{% url 'author:update_profile' request.user|slugify %}">Update Profile</a></li>
              <li><a href="{% url 'main:sign_out' %}">Sign Out</a></li>
            </ul>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>