mysite/author/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^@(?P<author_slug>[\w-]+)/$', views.show_profile, name='show_profile'),
    url(r'^@(?P<author_slug>[\w-]+)/update/$', views.update_profile, name='update_profile'),
]

mysite/main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.sign_in, name='sign_in'),
    url(r'^signout/$', views.sign_out, name='sign_out'),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls', namespace="main")),
    url(r'^', include('author.urls', namespace="author")),
    url(r'^', include('story.urls', namespace="story")),

]

if settings.DEBUG:
	urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/story/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^@(?P<author_slug>[\w-]+)/story/create/$', views.create_story, name='create_story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/edit/$', views.edit_story, name='edit_story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/$', views.story, name='story'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/chapter/create$', views.create_chapter, name='create_chapter'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/(?P<chapter_slug>[\w-]+)/edit$', views.edit_chapter, name='edit_chapter'),
    url(r'^@(?P<author_slug>[\w-]+)/(?P<story_slug>[\w-]+)/(?P<chapter_slug>[\w-]+)/$', views.chapter, name='chapter'),
    url(r'^home/$', views.home, name="home"),
    url(r'^topstories/$', views.top_stories, name="top_stories"),

]

mysite/author/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save, pre_save
from django.utils.text import slugify


# Defines upload location of Authors profile image
def upload_user_image(instance, filename):
    return "%s/%s" %(instance.user.username, filename)

"""
Defines Author class
One to One relation with User
"""


class Author(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, null=True)
    last_name = models.CharField(max_length=100, null=True)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    author_image = models.ImageField(upload_to=upload_user_image, height_field="height_field", width_field="width_field", null=True)
    author_bio = models.TextField(null=True)
    author_slug = models.SlugField(unique=True)

    # Object representation in Database
    def __str__(self):
        return self.user.username


# Function for creating slug using username
def create_user_slug(sender, instance, *args, **kwargs):
    instance.author_slug = slugify(instance.user.username)


# Django signal to save slug right before the Author object is saved
pre_save.connect(create_user_slug, sender=Author)


# Function to create Authors profile if not created or load if created
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = Author.objects.get_or_create(user=instance)

# Django signal to create Author profile(object) right after the User is created
post_save.connect(create_user_profile, sender=User)

mysite/author/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required
from .models import Author
from story.models import Story, Chapter


@login_required
def show_profile(request, author_slug=None):
    if not request.user.is_authenticated:
        raise Http404
    instance = get_object_or_404(Author, author_slug=author_slug)
    story_list = Story.objects.filter(author=instance)
    context = {
        "instance": instance,
        "story_list": story_list,
    }
    return render(request, "author/profile.html", context)


@login_required
def update_profile(request, author_slug=None):
    instance = get_object_or_404(Author, author_slug=author_slug)

    if request.user != instance.user:
        raise Http404
    if request.method == "POST":
        instance.first_name = request.POST.get('first_name')
        instance.last_name = request.POST.get('last_name')

        if request.FILES.get('image'):
            instance.author_image = request.FILES.get('image')

        instance.author_bio = request.POST.get('bio')
        instance.save()
        return redirect('story:home')
    context = {
        "instance": instance,
    }
    return render(request, 'author/update_profile.html', context)

mysite/templates/author/profile.html
{% extends "base.html" %}


{% block title %}
    Profile | {{instance.user.username}}
{% endblock %}


{% block content %}
    {{instance.user.username}}<br/>
    {{instance.first_name}}<br/>
    {{instance.last_name}}<br/>
    {{instance.user.email}}<br/>
    {{instance.author_bio}}<br/>
    {% if instance.author_image %}
        <img src="{{instance.author_image.url}}" alt="" width="10%" height="10%"/><br/>
    {% endif %}
    <hr/>
    <h2>Stories</h2>
    {% for story in story_list %}
        <a href="{% url 'story:story' story.author.user.username|slugify story.story_title|slugify %}">
            {{story.story_title}}
        </a><br/>
    {% endfor %}
{% endblock %}

mysite/templates/author/update_profile.html
{% extends "base.html" %}


{% block title %}
	Update | {{instance.user.username}}
{% endblock %}


{% block content %}
	<form method="POST" action="" id="profile-form" enctype="multipart/form-data">
		{% csrf_token %}
		<input type="text" name="first_name" placeholder="First Name" value="{{instance.first_name}}" required />
		<input type="text" name="last_name" placeholder="Last Name" value="{{instance.last_name}}" required />
		<img src="{{instance.author_image.url}}" alt="" width="10%" height="10%"/>
		<input type="file" name="image" accept="image/*"/>
		<input type="submit" value="Update" />
	</form>
	<textarea name="bio" form="profile-form" placeholder="Bio" required>{{instance.author_bio}}</textarea>
{% endblock %}